apiVersion: apps/v1
kind: Deployment
metadata:
  name: mett-dataportal-app-dev
  namespace: mett-dataportal-hl
  labels:
    app: mett-dataportal-app-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mett-dataportal-app-dev
  template:
    metadata:
      labels:
        app: mett-dataportal-app-dev
    spec:
      containers:
        - image: quay.io/microbiome-informatics/mett-dataportal-react-app:v0.0.145
          imagePullPolicy: Always
          name: mett-dataportal-app-dev
          env:
            - name: VITE_API_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: mett-app-config-dev
                  key: VITE_API_BASE_URL
            - name: VITE_ENA_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: mett-app-config-dev
                  key: VITE_ENA_BASE_URL
            - name: VITE_ASSEMBLY_INDEXES_PATH
              valueFrom:
                configMapKeyRef:
                  name: mett-app-config-dev
                  key: VITE_ASSEMBLY_INDEXES_PATH
            - name: VITE_GFF_INDEXES_PATH
              valueFrom:
                configMapKeyRef:
                  name: mett-app-config-dev
                  key: VITE_GFF_INDEXES_PATH
            - name: VITE_BACINTERACTOME_SHINY_APP_URL
              valueFrom:
                configMapKeyRef:
                  name: mett-app-config-dev
                  key: VITE_BACINTERACTOME_SHINY_APP_URL
          ports:
            - containerPort: 80
              name: react-app
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 20
            periodSeconds: 300
            successThreshold: 1
            failureThreshold: 3
      imagePullSecrets:
        - name: quay-pull-secret

---

apiVersion: v1
kind: Service§
metadata:
  name: mett-dataportal-app-dev-svc
  namespace: mett-dataportal-hl
  labels:
    app: mett-dataportal-app-dev
spec:
  type: NodePort
  selector:
    app: mett-dataportal-app-dev
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31028
