apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mett-pyhmmer-pvc-dev
  namespace: mett-dataportal-hl-dev
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 20Gi
  volumeName: mett-pyhmmer-pv-dev
  storageClassName: ""
