apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-dataportal-api-dev
  namespace: mett-dataportal-hl-dev
  labels:
    app: test-dataportal-api-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-dataportal-api-dev
  template:
    metadata:
      labels:
        app: test-dataportal-api-dev
    spec:
      securityContext:
        runAsUser: 7123
        runAsGroup: 1347
      containers:
        - image: quay.io/microbiome-informatics/mett-dataportal-api:v0.0.110a
          imagePullPolicy: Always
          name: test-dataportal-api-dev
          env:
            # Database configuration
            - name: ES_HOST
              valueFrom:
                configMapKeyRef:
                  name: mett-elasticsearch-config-dev
                  key: ES_HOST
            - name: ES_TIMEOUT
              valueFrom:
                configMapKeyRef:
                  name: mett-elasticsearch-config-dev
                  key: ES_TIMEOUT
            - name: ES_MAX_RETRIES
              valueFrom:
                configMapKeyRef:
                  name: mett-elasticsearch-config-dev
                  key: ES_MAX_RETRIES
            - name: ES_USER
              valueFrom:
                secretKeyRef:
                  name: mett-elasticsearch-credentials
                  key: ELASTIC_USERNAME
            - name: ES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mett-elasticsearch-credentials
                  key: ELASTIC_PASSWORD

            # Application-specific environment variables
            - name: DJANGO_DEBUG
              valueFrom:
                configMapKeyRef:
                  name: test-app-config-dev
                  key: DJANGO_DEBUG
            - name: TIME_ZONE
              valueFrom:
                configMapKeyRef:
                  name: test-app-config-dev
                  key: TIME_ZONE
            - name: ALLOWED_HOSTS
              valueFrom:
                configMapKeyRef:
                  name: test-app-config-dev
                  key: ALLOWED_HOSTS
            - name: DATA_PORTAL_URL
              valueFrom:
                configMapKeyRef:
                  name: test-app-config-dev
                  key: DATA_PORTAL_URL
            - name: ASSEMBLY_FTP_PATH
              valueFrom:
                configMapKeyRef:
                  name: test-app-config-dev
                  key: ASSEMBLY_FTP_PATH
            - name: GFF_FTP_PATH
              valueFrom:
                configMapKeyRef:
                  name: test-app-config-dev
                  key: GFF_FTP_PATH
          ports:
            - containerPort: 8000
              name: gunicorn
      imagePullSecrets:
        - name: quay-pull-secret

---

apiVersion: v1
kind: Service
metadata:
  name: test-dataportal-api-svc-dev
  namespace: mett-dataportal-hl-dev
  labels:
    app: test-dataportal-api-dev
spec:
  type: NodePort
  selector:
    app: test-dataportal-api-dev
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 31027
