apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mett-test-pyhmmer-pvc
  namespace: mett-dataportal-hl-dev
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: local-storage
  resources:
    requests:
      storage: 10Gi
