apiVersion: apps/v1
kind: Deployment
metadata:
  name: mett-dataportal-api-dev
  namespace: mett-dataportal-hl
  labels:
    app: mett-dataportal-api-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mett-dataportal-api-dev
  template:
    metadata:
      labels:
        app: mett-dataportal-api-dev
    spec:
      securityContext:
        runAsUser: 7123
        runAsGroup: 1347
      containers:
        - name: mett-dataportal-api-dev
          image: quay.io/microbiome-informatics/mett-dataportal-api
          imagePullPolicy: Always
          command: ["python"]
          args: ["manage.py", "runserver", "0.0.0.0:8000"]
          env:
            # Database configuration
            - name: DATAPORTAL_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: mett-postgres-config-dev
                  key: DATAPORTAL_DB_HOST
            - name: DATAPORTAL_DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: mett-postgres-config-dev
                  key: DATAPORTAL_DB_PORT
            - name: DATAPORTAL_DB
              valueFrom:
                configMapKeyRef:
                  name: mett-postgres-config-dev
                  key: DATAPORTAL_DB
            - name: DATAPORTAL_DB_USER
              valueFrom:
                configMapKeyRef:
                  name: mett-postgres-config-dev
                  key: DATAPORTAL_DB_USER
            - name: DATAPORTAL_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mett-postgres-secret-dev
                  key: DATAPORTAL_DB_PASSWORD
            # Elasticsearch configuration
            - name: ES_HOST
              valueFrom:
                configMapKeyRef:
                  name: mett-elasticsearch-config-dev
                  key: ES_HOST
            - name: ES_TIMEOUT
              valueFrom:
                configMapKeyRef:
                  name: mett-elasticsearch-config-dev
                  key: ES_TIMEOUT
            - name: ES_MAX_RETRIES
              valueFrom:
                configMapKeyRef:
                  name: mett-elasticsearch-config-dev
                  key: ES_MAX_RETRIES
            - name: ES_USER
              valueFrom:
                secretKeyRef:
                  name: mett-elasticsearch-credentials-dev
                  key: ELASTIC_USERNAME
            - name: ES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mett-elasticsearch-credentials-dev
                  key: ELASTIC_PASSWORD
            # Application-specific environment variables
            - name: DJANGO_DEBUG
              valueFrom:
                configMapKeyRef:
                  name: mett-app-config-dev
                  key: DJANGO_DEBUG
            - name: TIME_ZONE
              valueFrom:
                configMapKeyRef:
                  name: mett-app-config-dev
                  key: TIME_ZONE
            - name: ALLOWED_HOSTS
              valueFrom:
                configMapKeyRef:
                  name: mett-app-config-dev
                  key: ALLOWED_HOSTS
            - name: DATA_PORTAL_URL
              valueFrom:
                configMapKeyRef:
                  name: mett-app-config-dev
                  key: DATA_PORTAL_URL
            - name: ASSEMBLY_FTP_PATH
              valueFrom:
                configMapKeyRef:
                  name: mett-app-config-dev
                  key: ASSEMBLY_FTP_PATH
            - name: GFF_FTP_PATH
              valueFrom:
                configMapKeyRef:
                  name: mett-app-config-dev
                  key: GFF_FTP_PATH
            - name: CELERY_BROKER_URL
              valueFrom:
                configMapKeyRef:
                  name: mett-app-config-dev
                  key: CELERY_BROKER_URL
            - name: CELERY_RESULT_BACKEND
              valueFrom:
                configMapKeyRef:
                  name: mett-app-config-dev
                  key: CELERY_RESULT_BACKEND
          resources:
            requests:
              memory: "4Gi"
              cpu: "3"
            limits:
              memory: "8Gi"
              cpu: "4"
          ports:
            - containerPort: 8000
          livenessProbe:
            httpGet:
              path: /api/health
              port: 8000
              scheme: HTTP
              httpHeaders:
                - name: Host
                  value: 127.0.0.1
            initialDelaySeconds: 20
            periodSeconds: 300
            successThreshold: 1
            failureThreshold: 3
      imagePullSecrets:
        - name: quay-pull-secret

---

apiVersion: v1
kind: Service
metadata:
  name: mett-dataportal-api-dev-svc
  namespace: mett-dataportal-hl
  labels:
    app: mett-dataportal-api-dev
spec:
  type: NodePort
  selector:
    app: mett-dataportal-api-dev
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 31027
