apiVersion: v1
kind: ConfigMap
metadata:
  name: mett-app-config-dev
  namespace: mett-dataportal-hl
data:
  DJANGO_DEBUG: "False"
  TIME_ZONE: "Europe/London"
  ALLOWED_HOSTS: "www.gut-microbes.org,ebi.ac.uk,hh-rke-wp-webadmin-52-master-1.caas.ebi.ac.uk,localhost,127.0.0.1,hh-rke-wp-webadmin-52-master-1.caas.ebi.ac.uk:31028"
  DATA_PORTAL_URL: "127.0.0.1"
  ASSEMBLY_FTP_PATH: "https://ftp.ebi.ac.uk/pub/databases/mett/all_hd_isolates/deduplicated_assemblies"
  GFF_FTP_PATH: "https://ftp.ebi.ac.uk/pub/databases/mett/annotations/v1_2024-04-15/{}/functional_annotation/merged_gff"
  CELERY_BROKER_URL: "redis://mett-test-redis:6379/0"
  CELERY_RESULT_BACKEND: "redis://mett-test-redis:6379/1"
  REACT_APP_API_BASE_URL: "http://hh-rke-wp-webadmin-52-master-1.caas.ebi.ac.uk:31027/api"
  REACT_APP_ENA_BASE_URL: "https://www.ebi.ac.uk/ena/browser/view/"
  REACT_APP_ASSEMBLY_INDEXES_PATH: "https://ftp.ebi.ac.uk/pub/databases/metagenomics/temp/mett/dataportal/fasta_files"
  REACT_APP_GFF_INDEXES_PATH: "https://ftp.ebi.ac.uk/pub/databases/metagenomics/temp/mett/dataportal/gff3_files"
  REACT_APP_BACINTERACTOME_SHINY_APP_URL: "http://hh-rke-wp-webadmin-52-master-1.caas.ebi.ac.uk:30080/shiny-apps/app/bacinteractome"
  PYHMMER_FAA_BASE_PATH: "/data/pyhmmer/output/"
  HTTPS: "false"
