apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-dataportal-react-app-dev
  namespace: mett-dataportal-hl-dev
  labels:
    app: test-dataportal-react-app-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-dataportal-react-app-dev
  template:
    metadata:
      labels:
        app: test-dataportal-react-app-dev
    spec:
      containers:
        - image: quay.io/microbiome-informatics/mett-dataportal-react-app:v0.0.131a
          imagePullPolicy: Always
          name: test-dataportal-react-app-dev
          env:
            - name: REACT_APP_API_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: test-app-config-dev
                  key: REACT_APP_API_BASE_URL
            - name: REACT_APP_ENA_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: test-app-config-dev
                  key: REACT_APP_ENA_BASE_URL
            - name: REACT_APP_ASSEMBLY_INDEXES_PATH
              valueFrom:
                configMapKeyRef:
                  name: test-app-config-dev
                  key: REACT_APP_ASSEMBLY_INDEXES_PATH
            - name: REACT_APP_GFF_INDEXES_PATH
              valueFrom:
                configMapKeyRef:
                  name: test-app-config-dev
                  key: REACT_APP_GFF_INDEXES_PATH
            - name: REACT_APP_BACINTERACTOME_SHINY_APP_URL
              valueFrom:
                configMapKeyRef:
                  name: test-app-config-dev
                  key: REACT_APP_BACINTERACTOME_SHINY_APP_URL
          ports:
            - containerPort: 80
              name: react-app
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 20
            periodSeconds: 300
            successThreshold: 1
            failureThreshold: 3
      imagePullSecrets:
        - name: quay-pull-secret

---

apiVersion: v1
kind: Service
metadata:
  name: test-dataportal-react-app-svc-dev
  namespace: mett-dataportal-hl-dev
  labels:
    app: test-dataportal-react-app-dev
spec:
  type: NodePort
  selector:
    app: test-dataportal-react-app-dev
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31028
