apiVersion: apps/v1
kind: Deployment
metadata:
  name: mett-dataportal-app-prod
  namespace: mett-dataportal-hl
  labels:
    app: mett-dataportal-app-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mett-dataportal-app-prod
  template:
    metadata:
      labels:
        app: mett-dataportal-app-prod
    spec:
      containers:
        - image: quay.io/microbiome-informatics/mett-dataportal-react-app
          imagePullPolicy: Always
          name: mett-dataportal-app-prod
          env:
            - name: VITE_API_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: mett-app-config-prod
                  key: VITE_API_BASE_URL
            - name: VITE_ENA_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: mett-app-config-prod
                  key: VITE_ENA_BASE_URL
            - name: VITE_ASSEMBLY_INDEXES_PATH
              valueFrom:
                configMapKeyRef:
                  name: mett-app-config-prod
                  key: VITE_ASSEMBLY_INDEXES_PATH
            - name: VITE_GFF_INDEXES_PATH
              valueFrom:
                configMapKeyRef:
                  name: mett-app-config-prod
                  key: VITE_GFF_INDEXES_PATH
            - name: VITE_BACINTERACTOME_SHINY_APP_URL
              valueFrom:
                configMapKeyRef:
                  name: mett-app-config-prod
                  key: VITE_BACINTERACTOME_SHINY_APP_URL
            - name: VITE_PFAM_URL
              valueFrom:
                configMapKeyRef:
                  name: mett-app-config-prod
                  key: VITE_PFAM_URL
            - name: VITE_INTERPRO_URL
              valueFrom:
                configMapKeyRef:
                  name: mett-app-config-prod
                  key: VITE_INTERPRO_URL
            - name: VITE_KEGG_URL
              valueFrom:
                configMapKeyRef:
                  name: mett-app-config-prod
                  key: VITE_KEGG_URL
            - name: VITE_COG_URL
              valueFrom:
                configMapKeyRef:
                  name: mett-app-config-prod
                  key: VITE_COG_URL
          ports:
            - containerPort: 80
              name: react-app
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 20
            periodSeconds: 300
            successThreshold: 1
            failureThreshold: 3
      imagePullSecrets:
        - name: quay-pull-secret

---

apiVersion: v1
kind: Service
metadata:
  name: mett-dataportal-app-prod-svc
  namespace: mett-dataportal-hl
  labels:
    app: mett-dataportal-app-prod
spec:
  type: NodePort
  selector:
    app: mett-dataportal-app-prod
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31026
