apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gutmicrobes-hl-ingress
  namespace: mett-dataportal-hl
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - host: www.gut-microbes.org
      http:
        paths:
        - path: /api(/|$)(.*)
          pathType: Prefix
          backend:
            service:
              name: mett-dataportal-api-svc
              port:
                number: 8000

        - path: /api/docs
          pathType: Prefix
          backend:
            service:
              name: mett-dataportal-api-svc
              port:
                number: 8000

        #  /static-api/* to the django app
        - path: /api-static(/|$)(.*)
          pathType: Prefix
          backend:
            service:
              name: mett-dataportal-api-svc
              port:
                number: 8000

        #  /static/* to the React app
        - path: /static(/|$)(.*)
          pathType: Prefix
          backend:
            service:
              name: mett-dataportal-react-app-svc
              port:
                number: 80

        - path: /apidev(/|$)(.*)
          pathType: Prefix
          backend:
            service:
              name: mett-dataportal-api-svc-dev
              port:
                number: 8000

        - path: /apidev/docs
          pathType: Prefix
          backend:
            service:
              name: mett-dataportal-api-svc-dev
              port:
                number: 8000

        - path: /appdev(/|$)(.*)
          pathType: Prefix
          backend:
            service:
              name: mett-dataportal-react-app-svc-dev
              port:
                number: 80

        # All remaining routes to React app (client-side routing)
        - path: /
          pathType: Prefix
          backend:
            service:
              name: mett-dataportal-react-app-svc
              port:
                number: 80
