apiVersion: v1
kind: PersistentVolume
metadata:
  name: mett-pyhmmer-pv
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=3
  nfs:
    server: hh-isi-srv-vlan1496.ebi.ac.uk
    path: /ifs/public/metagenomics/mett/pyhmmer/prod

