apiVersion: apps/v1
kind: Deployment
metadata:
  name: mett-dataportal-api-dev
  namespace: mett-dataportal-hl-dev
  labels:
    app: mett-dataportal-api-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mett-dataportal-api-dev
  template:
    metadata:
      labels:
        app: mett-dataportal-api-dev
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "8000"
    spec:
      securityContext:
        runAsUser: 7123
        runAsGroup: 1347
      containers:
        - image: quay.io/microbiome-informatics/mett-dataportal-api:v0.0.136
          imagePullPolicy: Always
          name: mett-dataportal-api-dev
          env:
            # Database configuration
            - name: ES_HOST
              valueFrom:
                configMapKeyRef:
                  name: mett-elasticsearch-config-dev
                  key: ES_HOST
            - name: ES_TIMEOUT
              valueFrom:
                configMapKeyRef:
                  name: mett-elasticsearch-config-dev
                  key: ES_TIMEOUT
            - name: ES_MAX_RETRIES
              valueFrom:
                configMapKeyRef:
                  name: mett-elasticsearch-config-dev
                  key: ES_MAX_RETRIES
            - name: ES_USER
              valueFrom:
                secretKeyRef:
                  name: mett-elasticsearch-credentials
                  key: ELASTIC_USERNAME
            - name: ES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mett-elasticsearch-credentials
                  key: ELASTIC_PASSWORD

            # Application-specific environment variables
            - name: DJANGO_DEBUG
              valueFrom:
                configMapKeyRef:
                  name: mett-app-config-dev
                  key: DJANGO_DEBUG
            - name: TIME_ZONE
              valueFrom:
                configMapKeyRef:
                  name: mett-app-config-dev
                  key: TIME_ZONE
            - name: ALLOWED_HOSTS
              valueFrom:
                configMapKeyRef:
                  name: mett-app-config-dev
                  key: ALLOWED_HOSTS
            - name: DATA_PORTAL_URL
              valueFrom:
                configMapKeyRef:
                  name: mett-app-config-dev
                  key: DATA_PORTAL_URL
            - name: ASSEMBLY_FTP_PATH
              valueFrom:
                configMapKeyRef:
                  name: mett-app-config-dev
                  key: ASSEMBLY_FTP_PATH
            - name: GFF_FTP_PATH
              valueFrom:
                configMapKeyRef:
                  name: mett-app-config-dev
                  key: GFF_FTP_PATH
          ports:
            - containerPort: 8000
              name: gunicorn
          livenessProbe:
            httpGet:
              path: /api/health
              port: 8000
              scheme: HTTP
              httpHeaders:
                - name: Host
                  value: 127.0.0.1
            initialDelaySeconds: 20
            periodSeconds: 300
            successThreshold: 1
            failureThreshold: 3
      imagePullSecrets:
        - name: quay-pull-secret

---

apiVersion: v1
kind: Service
metadata:
  name: mett-dataportal-api-svc-dev
  namespace: mett-dataportal-hl-dev
  labels:
    app: mett-dataportal-api-dev
spec:
  type: NodePort
  selector:
    app: mett-dataportal-api-dev
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 31025
