apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mett-pyhmmer-pvc
  namespace: mett-dataportal-hl-dev
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 20Gi
