apiVersion: v1
kind: PersistentVolume
metadata:
  name: mett-postgres-pv-dev
  namespace: mett-dataportal-hl-dev
spec:
  storageClassName: standard-nfs-production
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/vikasg/Documents/ws/k8s-ws/postgres/data"
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mett-postgres-pvc-dev
  namespace: mett-dataportal-hl-dev
spec:
  storageClassName: standard-nfs-production
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

