# Generated by Django 5.2.1 on 2025-06-09 13:45

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("django_celery_results", "0014_alter_taskresult_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Database",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=32, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("seq", "Seq")], default="seq", max_length=16
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                ("version", models.CharField(max_length=32)),
                ("release_date", models.DateField(default=datetime.date.today)),
                ("order", models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name="HmmerJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "algo",
                    models.CharField(
                        choices=[("phmmer", "Phmmer")], default="phmmer", max_length=16
                    ),
                ),
                (
                    "database",
                    models.CharField(
                        choices=[
                            ("bu_type_strains", "BU Type Strains"),
                            ("bu_all", "BU All Strains"),
                            ("pv_type_strains", "PV Type Strains"),
                            ("pv_all", "PV All Strains"),
                            ("bu_pv_type_strains", "BU+PV Type Strains"),
                            ("bu_pv_all", "BU+PV All Strains"),
                        ],
                        max_length=32,
                    ),
                ),
                ("input", models.TextField()),
                (
                    "threshold",
                    models.CharField(
                        choices=[("evalue", "E-value"), ("bitscore", "Bit score")],
                        default="evalue",
                        max_length=16,
                    ),
                ),
                ("threshold_value", models.FloatField(default=1.0)),
                (
                    "task",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="django_celery_results.taskresult",
                    ),
                ),
            ],
        ),
    ]
