# Generated by Django 5.2.1 on 2025-06-19 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pyhmmer_search", "0002_pyhmmerdb"),
    ]

    operations = [
        migrations.AddField(
            model_name="hmmerjob",
            name="mx",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BLOSUM62", "Blosum62"),
                    ("BLOSUM45", "Blosum45"),
                    ("BLOSUM90", "Blosum90"),
                    ("PAM30", "Pam30"),
                    ("PAM70", "Pam70"),
                    ("PAM250", "Pam250"),
                ],
                default="BLOSUM62",
                max_length=16,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="hmmerjob",
            name="threshold",
            field=models.CharField(
                choices=[
                    ("evalue", "E-value"),
                    ("bitscore", "Bit score"),
                    ("cut_ga", "Cut GA"),
                ],
                default="evalue",
                max_length=16,
            ),
        ),
    ]
