# Generated by Django 5.2.1 on 2025-06-19 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pyhmmer_search", "0003_hmmerjob_mx_alter_hmmerjob_threshold"),
    ]

    operations = [
        migrations.AddField(
            model_name="hmmerjob",
            name="E",
            field=models.FloatField(blank=True, default=1.0, null=True),
        ),
        migrations.AddField(
            model_name="hmmerjob",
            name="T",
            field=models.FloatField(blank=True, default=7.0, null=True),
        ),
        migrations.AddField(
            model_name="hmmerjob",
            name="domE",
            field=models.FloatField(blank=True, default=1.0, null=True),
        ),
        migrations.AddField(
            model_name="hmmerjob",
            name="domT",
            field=models.FloatField(blank=True, default=5.0, null=True),
        ),
        migrations.AddField(
            model_name="hmmerjob",
            name="incE",
            field=models.FloatField(blank=True, default=0.01, null=True),
        ),
        migrations.AddField(
            model_name="hmmerjob",
            name="incT",
            field=models.FloatField(blank=True, default=25.0, null=True),
        ),
        migrations.AddField(
            model_name="hmmerjob",
            name="incdomE",
            field=models.FloatField(blank=True, default=0.03, null=True),
        ),
        migrations.AddField(
            model_name="hmmerjob",
            name="incdomT",
            field=models.FloatField(blank=True, default=22.0, null=True),
        ),
        migrations.AddField(
            model_name="hmmerjob",
            name="pextend",
            field=models.FloatField(blank=True, default=0.4, null=True),
        ),
        migrations.AddField(
            model_name="hmmerjob",
            name="popen",
            field=models.FloatField(blank=True, default=0.02, null=True),
        ),
        migrations.AlterField(
            model_name="hmmerjob",
            name="threshold",
            field=models.CharField(
                choices=[("evalue", "E-value"), ("bitscore", "Bit score")],
                default="evalue",
                max_length=16,
            ),
        ),
    ]
