# Generated by Django 5.2.1 on 2025-07-18 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "pyhmmer_search",
            "0004_hmmerjob_e_hmmerjob_t_hmmerjob_dome_hmmerjob_domt_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="hmmerjob",
            name="bias_filter",
            field=models.CharField(
                choices=[("on", "On"), ("off", "Off")],
                default="on",
                help_text="Bias composition filter setting",
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="hmmerjob",
            name="database",
            field=models.CharField(
                choices=[
                    ("bu_type_strains", "Bacteroides uniformis Type Strains"),
                    ("bu_all", "Bacteroides uniformis All Strains"),
                    ("pv_type_strains", "Phocaeicola vulgatus Type Strains"),
                    ("pv_all", "Phocaeicola vulgatus All Strains"),
                    (
                        "bu_pv_type_strains",
                        "Bacteroides uniformis + Phocaeicola vulgatus Type Strains",
                    ),
                    (
                        "bu_pv_all",
                        "Bacteroides uniformis + Phocaeicola vulgatus All Strains",
                    ),
                ],
                max_length=32,
            ),
        ),
    ]
