# Generated by Django 5.2.1 on 2025-07-18 14:11

from django.db import migrations


def update_database_names_to_full(apps, schema_editor):
    Database = apps.get_model("pyhmmer_search", "Database")

    # Update database names to full descriptive versions
    name_updates = {
        "bu_type_strains": "Bacteroides uniformis Type Strains",
        "bu_all": "Bacteroides uniformis All Strains",
        "pv_type_strains": "Phocaeicola vulgatus Type Strains",
        "pv_all": "Phocaeicola vulgatus All Strains",
        "bu_pv_type_strains": "Bacteroides uniformis + Phocaeicola vulgatus Type Strains",
        "bu_pv_all": "Bacteroides uniformis + Phocaeicola vulgatus All Strains",
    }

    for db_id, full_name in name_updates.items():
        try:
            database = Database.objects.get(id=db_id)
            database.name = full_name
            database.save()
        except Database.DoesNotExist:
            # Skip if database doesn't exist
            pass


def reverse_update_database_names_to_full(apps, schema_editor):
    Database = apps.get_model("pyhmmer_search", "Database")

    # Revert database names back to short versions
    name_reverts = {
        "bu_type_strains": "BU Type Strains",
        "bu_all": "BU All Strains",
        "pv_type_strains": "PV Type Strains",
        "pv_all": "PV All Strains",
        "bu_pv_type_strains": "BU+PV Type Strains",
        "bu_pv_all": "BU+PV All Strains",
    }

    for db_id, short_name in name_reverts.items():
        try:
            database = Database.objects.get(id=db_id)
            database.name = short_name
            database.save()
        except Database.DoesNotExist:
            # Skip if database doesn't exist
            pass


class Migration(migrations.Migration):

    dependencies = [
        ("pyhmmer_search", "0006_alter_database_name"),
    ]

    operations = [
        migrations.RunPython(
            update_database_names_to_full, reverse_update_database_names_to_full
        ),
    ]
