# Generated by Django 5.2.1 on 2025-08-11 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pyhmmer_search", "0007_update_database_names_to_full"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hmmerjob",
            name="bias_filter",
        ),
    ]
