# Generated by Django 5.2.8 on 2026-09-07 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pyhmmer_search", "0008_remove_bias_filter_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hmmerjob",
            name="database",
            field=models.CharField(
                choices=[
                    ("bu_type_strains", "Bacteroides uniformis Type Strains"),
                    ("bu_all", "Bacteroides uniformis All Strains"),
                    ("pv_type_strains", "Phocaeicola vulgatus Type Strains"),
                    ("pv_all", "Phocaeicola vulgatus All Strains"),
                    (
                        "bu_pv_type_strains",
                        "Bacteroides uniformis + Phocaeicola vulgatus Type Strains",
                    ),
                    ("bu_pv_all", "Bacteroides uniformis + Phocaeicola vulgatus All Strains"),
                    ("isolate_specific", "Isolate-Specific Database"),
                ],
                max_length=32,
            ),
        ),
    ]
