apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mett-elasticsearch-backup-nfs-pvc-dev
  namespace: mett-dataportal-hl-dev
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Gi
  volumeName: mett-elasticsearch-backup-nfs-pv-dev
  storageClassName: ""
