apiVersion: v1
kind: ConfigMap
metadata:
  name: mett-elasticsearch-config-dev
  namespace: mett-dataportal-hl-dev
data:
  ES_HOST: "http://hh-rke-wp-webadmin-52-master-1.caas.ebi.ac.uk:32467"
  ES_TIMEOUT: "30"
  ES_MAX_RETRIES: "5"
  elasticsearch.yml: |
    path.repo: ["/mnt/nfs_backups"]
    network.host: 0.0.0.0
