apiVersion: v1
kind: Service
metadata:
  name: mett-elasticsearch-service-dev
  namespace: mett-dataportal-hl-dev
spec:
  type: NodePort
  selector:
    app: mett-elasticsearch-dev
  ports:
    - name: http
      port: 9200
      targetPort: 9200
      nodePort: 32467