# Generated by Django 5.0.7 on 2024-08-13 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Species",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("scientific_name", models.CharField(max_length=255)),
                (
                    "common_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("taxonomy_id", models.IntegerField(unique=True)),
            ],
            options={
                "db_table": "species",
            },
        ),
        migrations.CreateModel(
            name="Strain",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("isolate_name", models.CharField(max_length=255)),
                (
                    "strain_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "assembly_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "assembly_accession",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("fasta_file", models.CharField(max_length=255)),
                ("gff_file", models.CharField(max_length=255)),
                (
                    "species",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="strains",
                        to="dataportal.species",
                    ),
                ),
            ],
            options={
                "db_table": "strain",
            },
        ),
        migrations.CreateModel(
            name="Gene",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("gene_id", models.CharField(max_length=255)),
                ("gene_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "gene_symbol",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("locus_tag", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "strain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="genes",
                        to="dataportal.strain",
                    ),
                ),
            ],
            options={
                "db_table": "gene",
            },
        ),
    ]
