apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mett-postgres-volume-claim
  namespace: mett-dataportal-hl-dev
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: mett-postgres-vol-1
