apiVersion: v1
kind: PersistentVolume
metadata:
  name: mett-postgres-vol-1
  namespace: mett-dataportal-hl-dev
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  mountOptions:
    - nfsvers=3
  nfs:
    server: hh-isi-srv-vlan1496.ebi.ac.uk
    path: /ifs/public/rw/metagenomics/mett-dataportal/dev/postgres
