export const HOMEPAGE_TEXT = {
    FEEDBACK: {
        MESSAGE: "We value your feedback! Help us improve by sharing your thoughts.",
        LINK: "https://www.ebi.ac.uk/about/contact/support/mett-feedback",
        LABEL: "Feedback"
    },
    NATURAL_QUERY: {
        TITLE: "Ask questions about genes and genomes in natural language",
        DESCRIPTION: "Try asking questions like 'Show me all essential genes in B. uniformis' or 'What are the functions of genes involved in carbohydrate metabolism?'",
        PLACEHOLDER: "Ask a question about genes and genomes...",
        BUTTON_TEXT: "Ask"
    },
    MAIN_CONTENT: {
        PARAGRAPH_1: "The transversal theme aims at mechanistically understanding the complex role that human-associated microbiomes play in human health and disease. Our current knowledge of bacterial gene functions come primarily from very few model bacteria, failing to capture the genetic diversity within the gut microbiome. One of the goals of METT is to systematically tackle the vast genetic matter in the gut microbiome and two establish new model microbes. The Flagship Project of METT has focused efforts on annotating the genomes of",
        B_UNIFORMIS: "B. uniformis (ATCC8492)",
        AND: "and",
        P_VULGATUS: "P. vulgatus (ATCC8482)",
        PARAGRAPH_1_CONTINUATION: ", two of the most prevalent and abundant bacterial species of the human microbiome.",
        PARAGRAPH_2: "The current version is a web-based Data Portal platform designed to browse the genomes of the the type strains",
        PARAGRAPH_2_CONTINUATION: ". The annotation data generated by the ME TT has been organised on the",
        FTP_SERVER_LINK: "FTP Server",
        PARAGRAPH_2_CONTINUATION_2: "hosted at EBI and contains structural annotations (such as Prokka and Mobilome predictions, etc) as well as functional annotations (including biosynthetic gene clusters, carbohydrate active enzymes, etc).",
        PARAGRAPH_3: "This data portal is powered by annotation results generated using the",
        METTANNOTATOR_LINK: "mettannotator release v1.0",
        METTANNOTATOR_URL: "https://github.com/EBI-Metagenomics/mettannotator/releases/tag/v1.0"
    }
}; 