apiVersion: apps/v1
kind: Deployment
metadata:
  name: mett-dataportal-app
  labels:
    app: mett-dataportal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mett-dataportal
  template:
    metadata:
      labels:
        app: mett-dataportal
    spec:
      volumes:
        - name: mett-dataportal-app-storage
          persistentVolumeClaim:
            claimName: mett-dataportal-volume-claim
      containers:
        - image: mett-dataportal
          imagePullPolicy: Never
          name: mett-dataportal
          ports:
            - containerPort: 8000
              name: gunicorn
          volumeMounts:
            - mountPath: "/app/data"
              name: mett-dataportal-app-storage
