apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mett-dataportal-volume-claim
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
