apiVersion: v1
kind: PersistentVolume
metadata:
  name: mett-dataportal-vol-1
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /data/mett-dataportal-vol-1/
