apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mett-elasticsearch-data-prod-0
  namespace: mett-dataportal-hl
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: standard-nfs-production
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mett-elasticsearch-data-prod-1
  namespace: mett-dataportal-hl
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: standard-nfs-production 