apiVersion: v1
kind: Service
metadata:
  name: mett-elasticsearch-service-prod
  namespace: mett-dataportal-hl
spec:
  type: NodePort
  selector:
    app: mett-elasticsearch-prod
  ports:
    - name: http
      port: 9200
      targetPort: 9200
      nodePort: 32457 