apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch-prod
  namespace: mett-dataportal-hl
spec:
  serviceName: elasticsearch-service-prod
  replicas: 2
  selector:
    matchLabels:
      app: elasticsearch-prod
  template:
    metadata:
      labels:
        app: elasticsearch-prod
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: elasticsearch-prod
              topologyKey: "kubernetes.io/hostname"
      initContainers:
        - name: init-fix-permissions
          image: busybox
          command: ["sh", "-c", "chown -R 1000:1000 /usr/share/elasticsearch/data && chmod -R 777 /usr/share/elasticsearch/data"]
          securityContext:
            runAsUser: 0  # Run as root to ensure it can modify permissions
          volumeMounts:
            - name: elasticsearch-data-prod
              mountPath: /usr/share/elasticsearch/data
      containers:
        - name: elasticsearch-prod
          image: docker.elastic.co/elasticsearch/elasticsearch:8.17.1
          ports:
            - containerPort: 9200
          env:
            - name: discovery.seed_hosts
              value: "elasticsearch-service-prod"
            - name: cluster.initial_master_nodes
              value: "elasticsearch-prod-0,elasticsearch-prod-1"
            - name: bootstrap.memory_lock
              value: "true"
            - name: xpack.security.enabled
              value: "true"
            - name: ELASTIC_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mett-elasticsearch-credentials-prod
                  key: ELASTIC_USERNAME
            - name: ELASTIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mett-elasticsearch-credentials-prod
                  key: ELASTIC_PASSWORD
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
          resources:
            requests:
              memory: "4Gi"
              cpu: "3"
            limits:
              memory: "8Gi"
              cpu: "4"
          volumeMounts:
            - name: elasticsearch-data-prod
              mountPath: /usr/share/elasticsearch/data
      volumes:
        - name: elasticsearch-data-prod
          persistentVolumeClaim:
            claimName: elasticsearch-data-prod-0


