apiVersion: v1
kind: ConfigMap
metadata:
  name: mett-elasticsearch-config
  namespace: mett-dataportal-hl
data:
  ES_HOST: "http://hh-rke-wp-webadmin-52-master-1.caas.ebi.ac.uk:32527"
  ES_TIMEOUT: "30"
  ES_MAX_RETRIES: "5"
