apiVersion: v1
kind: ConfigMap
metadata:
  name: mett-postgres-config
  namespace: mett-dataportal-hl-dev
data:
  DATAPORTAL_DB_HOST: "hh-rke-wp-webadmin-52-master-1.caas.ebi.ac.uk"
  DATAPORTAL_DB_PORT: "31508"
  DATAPORTAL_DB: "mett-dataportal-db"
  DATAPORTAL_DB_USER: "mett-dataportal-usr"

