apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mett-postgres-volume-claim
  namespace: mett-dataportal-hl-dev
spec:
  storageClassName: standard-nfs-production
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

