import React from 'react';
import styles from './HomeIntroSection.module.scss'; // Adjust the import path based on your directory structure

const HomeIntroSection: React.FC = () => {
  return (
      <section className="vf-grid vf-grid__col-3 | vf-card-container | vf-u-fullbleed">
        <div className="vf-section-header vf-grid__col--span-3">
          <div className="vf-grid__col--span-2">
            <div className={`vf-content ${styles.vfContent}`} style={{ textAlign: 'justify' }}> {}
              <p>
                The transversal theme aims at mechanistically understanding the complex role that human-associated
                microbiomes play in human health and disease. Our current knowledge of bacterial gene functions
                come primarily from very few model bacteria, failing to capture the genetic diversity
                within the gut microbiome. One of the goals of METT is to systematically tackle the vast
                genetic matter in the gut microbiome and two establish new model microbes.
                The Flagship Project of METT has focused efforts on annotating the genomes of
                <i>B. uniformis (ATCC8492)</i> and <i>P. vulgatus (ATCC8482)</i>, two of the most prevalent
                and abundant bacterial species of the human microbiome.
              </p>
              <p>
                The current version is a web-based <i>Data Portal</i> platform designed to
                browse the genomes of the the type strains
                <i>B. uniformis (ATCC8492)</i> and <i>P. vulgatus (ATCC8482)</i>.
                The annotation data generated by the ME TT has been organised on an FTP directory hosted at EBI
                and contains structural annotations (such as Prokka and Mobilome predictions, etc) as well as
                functional annotations (including biosynthetic gene clusters, carbohydrate active enzymes, etc).
              </p>
            </div>
          </div>
          <div>&nbsp;</div>
          <hr className="vf-divider"></hr>
        </div>
      </section>
  );
};

export default HomeIntroSection;
