# Generated by Django 5.1.2 on 2024-12-09 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dataportal", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneEssentiality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("media", models.CharField(max_length=50)),
                ("essentiality", models.CharField(max_length=50)),
                (
                    "gene",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="essentiality_data",
                        to="dataportal.gene",
                    ),
                ),
            ],
            options={
                "db_table": "gene_essentiality",
                "indexes": [
                    models.Index(fields=["media"], name="media_idx"),
                    models.Index(fields=["essentiality"], name="essentiality_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("gene", "media"), name="unique_gene_media"
                    )
                ],
            },
        ),
    ]
