# Generated by Django 5.1.2 on 2024-12-12 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dataportal", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="essentialitytag",
            name="label",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
