# Generated by Django 5.1.2 on 2024-12-10 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dataportal", "0003_geneessentiality"),
    ]

    operations = [
        migrations.AlterField(
            model_name="strain",
            name="type_strain",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
