# Generated by Django 5.1.2 on 2024-12-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dataportal", "0003_essentialitytag_label"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="geneessentiality",
            index=models.Index(
                fields=["essentiality", "media"], name="essentiality_media_idx"
            ),
        ),
    ]
