apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mett-dataportal-volume-claim
  namespace: mett-dataportal-hl-prod
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  volumeName: mett-dataportal-vol-1
