apiVersion: apps/v1
kind: Deployment
metadata:
  name: mett-dataportal-react-app-dev
  namespace: mett-dataportal-hl-dev
  labels:
    app: mett-dataportal-react-app-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mett-dataportal-react-app-dev
  template:
    metadata:
      labels:
        app: mett-dataportal-react-app-dev
    spec:
      containers:
        - image: quay.io/microbiome-informatics/mett-dataportal-react-app:v0.0.58
          imagePullPolicy: Always
          name: mett-dataportal-react-app-dev
          env:
            - name: REACT_APP_API_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: mett-app-config-dev
                  key: REACT_APP_API_BASE_URL
            - name: REACT_APP_ENA_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: mett-app-config-dev
                  key: REACT_APP_ENA_BASE_URL
            - name: REACT_APP_ASSEMBLY_INDEXES_PATH
              valueFrom:
                configMapKeyRef:
                  name: mett-app-config-dev
                  key: REACT_APP_ASSEMBLY_INDEXES_PATH
            - name: REACT_APP_GFF_INDEXES_PATH
              valueFrom:
                configMapKeyRef:
                  name: mett-app-config-dev
                  key: REACT_APP_GFF_INDEXES_PATH
          ports:
            - containerPort: 80
              name: react-app
      imagePullSecrets:
        - name: quay-pull-secret

---

apiVersion: v1
kind: Service
metadata:
  name: mett-dataportal-react-app-svc-dev
  namespace: mett-dataportal-hl-dev
  labels:
    app: mett-dataportal-react-app-dev
spec:
  type: NodePort
  selector:
    app: mett-dataportal-react-app-dev
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31026
