apiVersion: apps/v1
kind: Deployment
metadata:
  name: mett-dataportal-api-dev
  namespace: mett-dataportal-hl-dev
  labels:
    app: mett-dataportal-api-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mett-dataportal-api-dev
  template:
    metadata:
      labels:
        app: mett-dataportal-api-dev
    spec:
      securityContext:
        runAsUser: 7123
        runAsGroup: 1347
      containers:
        - image: quay.io/microbiome-informatics/mett-dataportal-api:v0.0.71
          imagePullPolicy: Always
          name: mett-dataportal-api-dev
          env:
            # Database configuration
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-dev
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-dev
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-dev
                  key: POSTGRES_DB
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-dev
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret-dev
                  key: POSTGRES_PASSWORD

            # Application-specific environment variables
            - name: DJANGO_DEBUG
              valueFrom:
                configMapKeyRef:
                  name: mett-app-config-dev
                  key: DJANGO_DEBUG
            - name: TIME_ZONE
              valueFrom:
                configMapKeyRef:
                  name: mett-app-config-dev
                  key: TIME_ZONE
            - name: ALLOWED_HOSTS
              valueFrom:
                configMapKeyRef:
                  name: mett-app-config-dev
                  key: ALLOWED_HOSTS
            - name: DATA_PORTAL_URL
              valueFrom:
                configMapKeyRef:
                  name: mett-app-config-dev
                  key: DATA_PORTAL_URL
            - name: ASSEMBLY_FTP_PATH
              valueFrom:
                configMapKeyRef:
                  name: mett-app-config-dev
                  key: ASSEMBLY_FTP_PATH
            - name: GFF_FTP_PATH
              valueFrom:
                configMapKeyRef:
                  name: mett-app-config-dev
                  key: GFF_FTP_PATH
          ports:
            - containerPort: 8000
              name: gunicorn
      imagePullSecrets:
        - name: quay-pull-secret

---

apiVersion: v1
kind: Service
metadata:
  name: mett-dataportal-api-svc-dev
  namespace: mett-dataportal-hl-dev
  labels:
    app: mett-dataportal-api-dev
spec:
  type: NodePort
  selector:
    app: mett-dataportal-api-dev
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 31025
