name: Production - Build and Publish ME TT Data Portal Images (Django APIs & React App)

on:

  workflow_dispatch:

jobs:
  # Job to build and push Django API image
  prod-build-and-push-django:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ github.ref_name }}
    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Quay.io
        env:
          DOCKER_CONFIG_JSON: ${{ secrets.QUAY_DOCKER_CONFIG }}
        run: |
          echo "$DOCKER_CONFIG_JSON" > ~/.docker/config.json

      - name: Build the Django Docker image
        run: |
          docker build -t quay.io/microbiome-informatics/mett-dataportal-api:${{ env.IMAGE_TAG }} -f ./dataportal_api/Dockerfile .

      - name: Push the Django Docker image
        run: |
          docker push quay.io/microbiome-informatics/mett-dataportal-api:${{ env.IMAGE_TAG }}

  # Job to build and push React app image
  prod-build-and-push-react:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ github.ref_name }}
    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Quay.io
        env:
          DOCKER_CONFIG_JSON: ${{ secrets.QUAY_DOCKER_CONFIG }}
        run: |
          echo "$DOCKER_CONFIG_JSON" > ~/.docker/config.json

      - name: Build the React Docker image
        run: |
          docker build -t quay.io/microbiome-informatics/mett-dataportal-react-app:${{ env.IMAGE_TAG }} -f ./dataportal-app/Dockerfile .

      - name: Push the React Docker image
        run: |
          docker push quay.io/microbiome-informatics/mett-dataportal-react-app:${{ env.IMAGE_TAG }}
